opensearch-project/ml-commons-dashboards

public/components/experiment_warning/__tests__/index.test.tsx, public/components/experiment_warning/index.tsx, public/components/monitoring/model_deployment_table.tsx, public/components/monitoring/tests/model_deployment_table.test.tsx
update link address for Machine Learning Documentation and forum.opensearch.org
=> feat: update link address

public/components/monitoring/index.scss, public/components/monitoring/model_deployment_table.tsx, public/components/monitoring/tests/model_deployment_table.test.tsx, public/components/preview_panel/nodes_table.scss, public/components/preview_panel/nodes_table.tsx
Update the table cell text copy interaction according the figma
=> feat: update table cell text copy interaction

public/components/model_list/__tests__/upload_callout.test.tsx, public/components/model_list/index.tsx, public/components/model_list/upload_callout.tsx
1. add upload callout for model group list table
=> feat: add upload callout

public/components/register_model/register_model.tsx
=> fix: update-register-form-hearder-descriptions

.github/workflows/lint-workflow.yml, .github/workflows/unit-tests-workflow.yml
=> ci: update GitHub workflows OSD version to main

package.json, public/components/register_model/__tests__/model_file_uploader_manager.test.ts, public/components/register_model/__tests__/register_model.hooks.test.ts, public/components/register_model/__tests__/register_model_artifact.test.tsx, public/components/register_model/__tests__/register_model_form.test.tsx, public/components/register_model/constants.ts, public/components/register_model/model_file_upload_manager.ts, public/components/register_model/register_model.hooks.ts, public/components/register_model/register_model.tsx, yarn.lock
+ display notification if file upload failed/succeed
+ add rxjs
=> feat: upload file after register form submitted

release-notes/opensearch-ml-commons-dashboards.release-notes-2.6.0.0.md
Change Features to Experimental Features
=> docs: change Features to Experimental Features

common/constant.ts, public/components/register_model/__tests__/register_model_artifact.test.tsx, public/components/register_model/artifact.tsx, public/components/register_model/artifact_file.tsx
+ set file size limit to 4GB
+ only allow ZIP(.zip) file
=> feat: update artifact file validation rules

.github/workflows/lint-workflow.yml, .github/workflows/unit-tests-workflow.yml
update workflow OSD version to 2.x
=> ci: update workflow OSD version to 2.x

public/components/register_model/__tests__/register_model_artifact.test.tsx, public/components/register_model/__tests__/register_model_details.test.tsx, public/components/register_model/__tests__/register_model_metrics.test.tsx, public/components/register_model/__tests__/register_model_tags.test.tsx, public/components/register_model/__tests__/register_model_version_notes.test.tsx, public/components/register_model/__tests__/setup.tsx
=> fix: tweak test mocks

public/components/register_model/__tests__/error_call_out.test.tsx, public/components/register_model/__tests__/register_model_configuration.test.tsx, public/components/register_model/__tests__/register_model_details.test.tsx, public/components/register_model/__tests__/register_model_form.test.tsx, public/components/register_model/__tests__/setup.tsx, public/components/register_model/artifact.tsx, public/components/register_model/artifact_file.tsx, public/components/register_model/constants.ts, public/components/register_model/error_call_out.tsx, public/components/register_model/error_message.tsx, public/components/register_model/model_configuration.tsx, public/components/register_model/model_details.tsx, public/components/register_model/register_model.tsx
Display error call-out after the first time trying to submit the form but with errors
=> feat: add form error call-out

.codecov.yml, .github/workflows/unit-tests-workflow.yml, README.md, test/jest.config.js
=> test: enable codecov

opensearch_dashboards.json, package.json, release-notes/opensearch-ml-commons-dashboards.release-notes-2.7.0.0.md
Signed-off-by: Yulong Ruan <ruanyl@amazon.com>
=> bump to 2.7.0

release-notes/opensearch-ml-commons-dashboards.release-notes-2.7.0.0.md
=> doc: add 2.7.0 release notes

public/apis/model.ts, public/components/common/forms/__tests__/model_version_notes_field.test.tsx, public/components/common/forms/model_version_notes_field.tsx, public/components/model/types.ts, public/components/model_version/__tests__/version_information.test.tsx, public/components/model_version/model_version.tsx, public/components/model_version/types.ts, public/components/model_version/version_information.tsx, public/components/register_model/model_version_notes.tsx, public/components/register_model/register_model.types.ts
=> feat(ui): version information edit component

release-notes/opensearch-ml-commons-dashboards.release-notes-2.8.0.0.md
=> doc: add release notes for 2.8.0

common/model_version.ts, public/apis/model_version.ts, public/components/__tests__/global_breadcrumbs.test.tsx, public/components/common/modals/__tests__/model_version_deployment_confirm_modal.test.tsx, public/components/common/modals/model_version_deployment_confirm_modal.tsx, public/components/model/__tests__/model.test.tsx, public/components/model_version/__tests__/toggle_deploy_button.test.tsx, public/components/model_version/model_version.tsx, public/components/model_version/toggle_deploy_button.tsx, public/components/model_version/version_details.tsx, public/components/register_model/__tests__/register_model_form.test.tsx, public/components/register_model/register_model.tsx, public/hooks/tests/use_deployment.test.ts, public/hooks/use_deployment.tsx, test/mocks/model_handlers.ts, test/mocks/model_version_handlers.ts, test/mocks/task_handlers.ts, test/test_utils.tsx
=> feat: deploy and undeploy api integration

server/services/model_version_service.ts
=> fix: map model_group_id to model_id

public/components/monitoring/index.tsx, public/components/monitoring/tests/index.test.tsx
Remove duration picker background in dark mode to fix #206  
=> remove background for dark mode to fix #206

public/components/experiment_warning/__tests__/index.test.tsx, public/components/experiment_warning/index.tsx, public/components/monitoring/model_deployment_table.tsx, public/components/monitoring/tests/model_deployment_table.test.tsx
Update ml document link address to fix #208
=> Fix ml document link address

public/components/experiment_warning/index.tsx, public/components/monitoring/model_deployment_table.tsx
Open external links use new blank tab
=> feat: open external link in blank page

public/components/common/modals/index.ts, public/components/common/modals/model_delete_confirm_modal.tsx, public/components/model/__tests__/model.test.tsx, public/components/model/model.tsx, public/components/model/model_delete_button.tsx, public/components/model_list/index.tsx, public/components/model_list/model_table.tsx, public/components/model_list/model_table_row_delete_button.tsx
=> Feat add basic model delete

public/components/common/modals/__tests__/model_version_deployment_confirm_modal.test.tsx, public/components/common/modals/model_version_deployment_confirm_modal.tsx, public/components/model/model_versions_panel/__tests__/model_version_table_row_actions.test.tsx, public/components/model/model_versions_panel/model_version_table.tsx, public/components/model/model_versions_panel/model_version_table_row_actions.tsx, public/components/model/model_versions_panel/model_versions_panel.tsx
Update model version data after deploy and undeploy complete
=> feat: refresh model version data after deploy or undeploy complete

public/components/common/forms/model_name_field.tsx
=> fix: fix error when search for model name when index hasn't created

.github/workflows/experimental-release.yml
=> build: add experimental release action

public/apis/model.ts, public/components/monitoring/use_monitoring.ts, server/routes/model_router.ts, server/services/model_service.ts, server/services/utils/model.ts
Exclude remote models in overview page
=> feat: exclude remote model for admin UI

public/apis/model.ts, public/components/monitoring/model_deployment_table.tsx, public/components/monitoring/tests/model_deployment_table.test.tsx, public/components/monitoring/tests/use_monitoring.test.ts, public/components/monitoring/use_monitoring.ts, public/components/preview_panel/__tests__/preview_panel.test.tsx, public/components/preview_panel/index.tsx, server/routes/model_router.ts, server/services/model_service.ts, server/services/utils/model.ts
1. Rollback filter out REMOTE models
2. Add source field to distinguish local and external model
=> Add source field to distinguish local and external model

public/components/monitoring/tests/use_monitoring.test.ts, public/components/monitoring/use_monitoring.ts
Fix #236 , reset to first page after name or state change.
=> Fix no model show up when search a model

public/components/preview_panel/connector_details.tsx, public/components/preview_panel/index.tsx
update ui component according to designer and add fallback string
=> update ui component according to designer and add fallback string

public/components/preview_panel/connector_details.tsx, public/components/preview_panel/index.tsx
[Backport 2.x] update ui component according to designer and add fallback string #254
=> [Backport 2.x] update ui component according to designer and add fallback string #254

release-notes/opensearch-ml-commons-dashboards.release-notes-2.10.0.0.md
=> doc: add release notes for 2.10

release-notes/opensearch-ml-commons-dashboards.release-notes-2.11.0.0.md
Add release notes for 2.11.0.0
=> doc: add release notes for 2.11.0.0

release-notes/opensearch-ml-commons-dashboards.release-notes-2.12.0.0.md
=> docs: add release notes for 2.12

release-notes/opensearch-ml-commons-dashboards.release-notes-2.13.0.0.md
=> doc: add release notes for 2.13

release-notes/opensearch-ml-commons-dashboards.release-notes-2.14.0.0.md
=> Add 2.14 release notes

release-notes/opensearch-ml-commons-dashboards.release-notes-2.15.0.0.md
=> Add release notes for 2.15

public/plugin.ts
Update registered nav link category to Machine learning
=> Update category to Machine learning

release-notes/opensearch-ml-commons-dashboards.release-notes-2.16.0.0.md
=> Add release notes for 2.16.0

server/routes/__tests__/connector_router.test.ts, server/routes/connector_router.ts, server/routes/router.mock.ts
Return 400 instead of 500 when error occurred in connector router
=> Fix connector router response 500

release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.0.0.md
=> doc: add release notes for 2.17

release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.0.0.md
This PR is for removing not released bug fix notes
=> Remove not released bug fix notes

release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.1.0.md
Add release notes for 2.17.1.0
=> Add release notes for 2.17.1.0

release-notes/opensearch-ml-commons-dashboards.release-notes-2.18.0.0.md
Add release notes for 2.18.0 release
A part of #368 
=> Add 2.18.0 release notes

release-notes/opensearch-ml-commons-dashboards.release-notes-2.19.0.0.md
=> Add 2.19.0 release notes

release-notes/opensearch-ml-commons-dashboards.release-notes-2.19.0.0.md
Update 2.19 release notes for cross-spawn bump
=> Update 2.19 release notes for cross-spawn bump

release-notes/opensearch-ml-commons-dashboards.release-notes-3.0.0.0-alpha1.md
Add release notes for 3.0.0.0-alpha1
=> Add release notes for 3.0.0.0-alpha1

.github/workflows/verify-binary-installation.yml, opensearch_dashboards.json, package.json
Increment version to 3.0.0.0-beta1
=> Increment version to 3.0.0.0-beta1

release-notes/opensearch-ml-commons-dashboards.release-notes-3.0.0.0-beta1.md
Add `3.0.0.0-beta1` release notes.
=> Add 3.0.0.0-beta1 release notes

release-notes/opensearch-ml-commons-dashboards.release-notes-3.0.0.0-beta1.md
=> Update release notes for #411

.github/workflows/verify-binary-installation.yml
Fix verify install binary workflow failed, all checks can be passed now.
=> Fix verify install binary workflow failed

release-notes/opensearch-ml-commons-dashboards.release-notes-3.0.0.0.md
=> Add 3.0.0.0 release notes

release-notes/opensearch-ml-commons-dashboards.release-notes-3.1.0.0.md
=> Add release notes for 3.1.0
