opensearch-project/ml-commons-dashboards

.github/workflows/lint-workflow.yml
.github/workflows/unit-tests-workflow.yml

The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.

Fix Node.js and Yarn installation in CI

---

public/components/register_model/__tests__/register_model_details.test.tsx
public/components/register_model/__tests__/register_model_version_notes.test.tsx
public/components/register_model/model_details.tsx
public/components/register_model/model_version_notes.tsx

The restriction is applied to:
1. Model name input
2. Model description input
3. Model note input
+ The react-hook-form validation rules on these inputs are removed
+ Renamed `isUniqueModelName` to `isDuplicateModelName`
Signed-off-by: Yulong Ruan <ruanyl@amazon.com>

feat: disallow user to type if text exceed max length

---

public/components/register_model/__tests__/register_model_artifact.test.tsx
public/components/register_model/__tests__/register_model_file_format.test.tsx
public/components/register_model/__tests__/setup.tsx
public/components/register_model/artifact.tsx
public/components/register_model/constants.ts
public/components/register_model/register_model.tsx
public/components/register_model/register_model.types.ts

Added a new register model form field: model file format select which allows user to select from ONNX or Torchscript
Signed-off-by: Yulong Ruan <ruanyl@amazon.com>

feat: add model file format select

---

public/components/preview_panel/__tests__/preview_panel.test.tsx
public/components/preview_panel/index.tsx

To fix #145 , render empty ML nodes while calling model profile API
#145 

fix: avoid ml nodes show not responding during loading (#145)

---

common/model.ts
public/components/monitoring/tests/use_monitoring.test.ts

This PR updates the model status labels according to the ml-commons breaking changes introduced in 2.7: https://github.com/opensearch-project/ml-commons/pull/822

fix: update model status labels according to the API change in 2.7

---

public/components/register_model/__tests__/error_call_out.test.tsx
public/components/register_model/__tests__/register_model_artifact.test.tsx
public/components/register_model/__tests__/register_model_configuration.test.tsx
public/components/register_model/__tests__/register_model_details.test.tsx
public/components/register_model/__tests__/register_model_file_format.test.tsx
public/components/register_model/__tests__/register_model_tags.test.tsx
public/components/register_model/__tests__/register_model_version_notes.test.tsx
public/components/register_model/__tests__/setup.tsx
public/components/register_model/__tests__/tag_type_popover.test.tsx
public/components/register_model/model_tags.tsx
public/components/register_model/register_model.hooks.ts
public/components/register_model/register_model.tsx
public/components/register_model/register_model.types.ts
public/components/register_model/tag_field.tsx
public/components/register_model/tag_type_popover.tsx

Add tag type to model tag field component, user can select tag type from `number` or `string`
Signed-off-by: Yulong Ruan <ruanyl@amazon.com>### Description

feat: support for adding tag types

---

.github/CODEOWNERS
MAINTAINERS.md

The group is going away, fixing the list.

Fix: CODEOWNERS.

---

.husky/pre-commit
package.json
yarn.lock

The `execa` will cause GMS-2020-2 advisor.
The old `husky` depends on it, update the `husky` to 8.0.3 , then we won't use `execa` anymore.
After this PR merged, we need to re-run `yarn` to upgrade the `husky` version.  

chore: update husky to 8.0.3 to avoid use execa

---

release-notes/opensearch-ml-commons-dashboards.release-notes-2.9.0.0.md

doc: add release notes for 2.9.0

---

public/components/preview_panel/__tests__/connector_details.test.tsx
public/components/preview_panel/__tests__/nodes_table.test.tsx
public/components/preview_panel/__tests__/preview_panel.test.tsx
public/components/preview_panel/connector_details.tsx
public/components/preview_panel/index.tsx
public/components/preview_panel/nodes_table.tsx

update preview panel for external models

update preview panel for external models

---

public/components/monitoring/model_deployment_table.tsx
public/components/monitoring/tests/model_deployment_table.test.tsx
public/components/preview_panel/__tests__/connector_details.test.tsx
public/components/preview_panel/connector_details.tsx

feat: replace dash with em dash

---

.github/workflows/unit-tests-workflow.yml

Onboard jenkins build docker image to ml-commons-dashboards github ci checks
https://github.com/opensearch-project/ml-commons-dashboards/issues/274

Onboard jenkins build docker image to ml-commons-dashboards github ci checks

---

.github/workflows/unit-tests-workflow.yml

Onboard jenkins build docker image to ml-commons-dashboards github ci checks 2.x
Backport #280.
https://github.com/opensearch-project/ml-commons-dashboards/issues/274

[Backport #280] Onboard jenkins build docker image to ml-commons-dashboards github ci checks

---

.github/workflows/verify-binary-installation.yml

I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
https://github.com/opensearch-project/dashboards-observability/pull/309
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5952
For more …

Add new workflow to verify binary install

---

public/components/monitoring/__tests__/use_monitoring.test.tsx
public/components/monitoring/use_monitoring.ts

This PR for fixing two bugs.
1. Reset current page after data source change.
2. Clear `params.nameOrId` after resetSearch called

Reset current page after data source change

---

public/components/monitoring/__tests__/use_monitoring.test.tsx
public/components/monitoring/use_monitoring.ts

The PR is for fixing page always stay empty page when jump to no models page. This error always happens in below flow:
1. User visit deployed models list and total pages are 2.
2. User jump to 2 page, but the deployed models changed and total pages become 1.
3. Then the page will always stay empty page like below image
After this PR, the current page will reset to max page and resend the request. It will jump to page 1 in above cases.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTIN …

Reset to max page when current page overflow

---

opensearch_dashboards.json
public/components/data_source_top_nav_menu.tsx
public/utils/__tests__/data_source.test.ts
public/utils/data_source.ts

Add version decoupling meta data for MDS, a part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877

Add version decoupling meta for MDS

---

public/components/common/copyable_text.tsx
public/components/common/options_filter/options_filter.tsx
public/components/common/refresh_interval.tsx
public/components/monitoring/model_deployment_table.tsx
public/components/monitoring/search_bar.tsx
public/components/status_filter/index.tsx

Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.

Use smaller and compressed varients of buttons and form components

---

public/components/monitoring/model_deployment_table.tsx
public/components/preview_panel/connector_details.tsx
public/components/preview_panel/index.tsx
public/components/preview_panel/nodes_table.tsx

- Using small text for flyout header title

Align font size and style

---

public/plugin.ts
release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.0.0.md

This PR is for fixing the category order and description in the data administration landing page. These two kind of things will be updated like below image:

Fix category order and description in data administration landing page

---

public/components/common/refresh_interval.tsx
public/components/monitoring/index.tsx
public/components/monitoring/monitoring_page_header.tsx

This PR is for reducing spacing in AI models table when new home page enabled, mainly include below updates:
1. Reduce spacing between search bar and filters to 8px
2. Remove spacing between search bar and panel top
3. Add fixed width to `RefreshInterval` avoid input overflow 
This PR also include one bug fixing for refresh with a very large number. The refresh API will be called many times after input a very large delay number.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#d …

Reduce machine learning table spacing when new home page enabled

---

.github/workflows/verify-binary-installation.yml
opensearch_dashboards.json
package.json

Bump opensearch to 3.0.0.0-alpha1, according https://github.com/opensearch-project/dashboards-query-workbench/pull/444
A part of #234 

Bump opensearch to 3.0.0.0-alpha1

---

public/utils/__tests__/data_source.test.ts
public/utils/data_source.ts

This PR is for fixing the data source compatible setting in the data source selector. The data source selector can working fine with pre-release such as `3.0.0-alpha1` or `3.0.0-beta1`.

Fix data source not compatible with prerelease
